---
- block:

  - name: Upgrade host
    ovirt_hosts:
      auth: "{{ ovirt_auth }}"
      name: "{{ item.name }}"
      state: upgraded
      timeout: 1200
    register: host_upgraded

  rescue:
    - name: Report issues
      fail:
        msg: "Upgrade of host '{{ item.name }}' failed :( ."
      ignore_errors: true

    - name: Set the operation to fail
      set_fact:
        upgrade_failed: true
