---
- name: Create VMs
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ item.profile.cluster }}"
    template: "{{ item.profile.template }}"
    name: "{{ item.name }}"
    memory: "{{ item.profile.memory }}"
    cpu_cores: "{{ item.profile.cores }}"
    cloud_init:
      nic_name: eth0
      nic_boot_protocol: dhcp
      nic_on_boot: true
      host_name: "{{ item.name }}.{{ item.profile.domain }}"
      authorized_ssh_keys: "{{ vm_ssh_key }}"
      # This is hack, because ovirt-guest-agent fail to start on my rhel7 qcow2 image
      # it doesn't work only on master (4.2) engine version
      custom_script: |
        runcmd:
          - [ 'ln', '-s', '/dev/vport2p1', '/dev/virtio-ports/com.redhat.rhevm.vdsm' ]
          - [ 'chown', 'ovirtagent:ovirtagent', '/dev/virtio-ports/com.redhat.rhevm.vdsm' ]
          - [ 'systemctl', 'restart', 'ovirt-guest-agent.service' ]
      user_name: root
      root_password: "{{ item.profile.root_password }}"
  with_items:
    - "{{ vms }}"
  async: 800
  poll: 0
  register: all_vms
  tags:
    - ovirt-virt-infra

- name: Wait for VMs to be added
  async_status: "jid={{ item.ansible_job_id }}"
  register: job_result
  with_items:
    - "{{ all_vms.results }}"
  until: job_result.finished
  retries: 40
  delay: 20
  tags:
    - ovirt-virt-infra

- name: Create VMs disks
  ovirt_disks:
    auth: "{{ ovirt_auth }}"
    name: "{{ item.0.name }}_{{ item.1.name }}"
    vm_name: "{{ item.0.name }}"
    size: "{{ item.1.size }}"
    format: "{{ item.1.format | default(omit) }}"
    interface: "{{ item.1.interface | default(omit) }}"
    storage_domain: "{{ item.1.storage_domain | default(omit) }}"
  with_subelements:
    - "{{ vms }}"
    - profile.disks
  tags:
    - ovirt-virt-infra

- name: Tag VMs
  ovirt_tags:
    auth: "{{ ovirt_auth }}"
    name: "{{ item }}"
    vms: "{{ vms|json_query(query)|map(attribute='name') | list }}"
    #vms: []
  with_items:
    - "{{ vms | map(attribute='tag') | list | unique }}"
  vars:
    query: "[?tag=='{{ item }}']"
  tags:
    - ovirt-virt-infra

- name: Wait for VMs IP
  ovirt_vms_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ item.name }}"
    fetch_nested: true
    nested_attributes: ips
  with_items:
    - "{{ vms }}"
  until: ovirt_vms | map(attribute='reported_devices') | list | first | length > 0
  retries: 5
  delay: 5
  when: "{{ wait_for_ip | default(true) }}"
  tags:
    - wait_for_ip
    - ovirt-virt-infra
