---
- name: Add data center
  ovirt_datacenters:  
    auth: "{{ ovirt_auth }}"
    state: present
    name: "{{ data_center_name }}"
    description: "{{ data_center_description | default(omit) }}"
    local: "{{ data_center_local | default(false) }}"
    compatibility_version: "{{ compatibility_version }}"
  tags:
    - datacenters
