- name: oVirt image template
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: https://ondra.local/ovirt-engine/api
    engine_user: admin@internal
    engine_password: 123456
    engine_cafile: /home/omachace/Downloads/ca.pem

    qcow_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    template_cluster: production
    template_name: centos7_template
    template_memory: 2GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: nfs

  roles:
    - ovirt-image-template
