---
- name: oVirt infra
  #hosts: engine
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    engine_url: https://ondra.local/ovirt-engine/api
    engine_user: admin@internal
    engine_password: 123456
    engine_cafile: /home/omachace/ovirt-engine41/etc/pki/ovirt-engine/ca.pem
    engine_insecure: false

    cluster_name: production
    
  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  roles:
    - ovirt-cluster-upgrade

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always 
