---
###########################
# REST API variables
###########################
engine_url: https://engine/ovirt-engine/api
engine_user: admin@internal
engine_password: 123
engine_cafile: /etc/pki/ovirt-engine/ca.pem
engine_insecure: false

###########################
# Common
###########################
compatibility_version: 4.2

# Data center
data_center_name: mydatacenter

###########################
# Clusters
###########################
clusters:
 - name: development
   cpu_type: Intel Conroe Family
   profile: development
 - name: production
   cpu_type: Intel Conroe Family
   profile: production

###########################
# Hosts
###########################
hosts:
  - name: myhost1
    address: 192.168.200.2
    cluster: development
    password: 123456
  - name: myhost2
    address: 192.168.200.4
    cluster: production
    password: 123456

###########################
# Storage
###########################
storages:
  nfs:
    master: true
    state: present
    nfs:
      address: 192.168.200.3
      path: /exports/nfs/share1
  iscsi:
    state: present
    iscsi:
      target: iqn.2014-07.org.ovirt:storage
      port: 3260
      address: 192.168.200.3
      username: username
      password: password
      lun_id: 36001405c236fbeed27a4ceb8dcefc872
  templates:
    domain_function: export
    nfs:
      address: 192.168.200.3
      path: /exports/nfs/exported
  iso:
    domain_function: iso
    nfs:
      address: 192.168.200.3
      path: /exports/nfs/iso

###########################
# Networks
###########################
logical_networks:
  - name: mynetwork
    clusters:
      - name: development
        assigned: yes
        required: no
        display: no
        migration: yes
        gluster: no

host_networks:
  - name: myhost1
    check: true
    save: true
    bond:
      name: bond0
      mode: 2
      interfaces:
        - eth2
        - eth3
    networks:
      - name: mynetwork
        boot_protocol: dhcp

###########################
# Users & Groups
###########################
aaa_profile_type: 389ds
aaa_user: uid=user1,ou=People,dc=lago,dc=local
aaa_password: 123456
aaa_profile_name: testldap
aaa_ldap:
  - 192.168.200.3

users:
  - name: user1
    authz_name: internal-authz
    password: 1234568
    valid_to: "2018-01-01 00:00:00Z"
  - name: user2
    authz_name: internal-authz
    password: 1234568
    valid_to: "2018-01-01 00:00:00Z"

user_groups:
  - name: group1
    authz_name: internal-authz
    users:
      - user1

permissions:
  - state: present
    user_name: user1
    authz_name: internal-authz
    role: UserRole
    object_type: cluster
    object_name: development

  - state: present
    group_name: group1
    authz_name: internal-authz
    role: UserRole
    object_type: cluster
    object_name: production
